### ISSUE TITLE
Sum type encoder in the README

### ISSUE THREAD

**Issue by ysangkok** [NorfairKing/autodocodec#13]
I think it would be super useful to show in the readme how to make a schema for a sum type like e.g. `data Color = Black | White` that doesn't use DeriveGeneric. I imagine there must be an analogue of `requiredField` that takes a deserializer like `HasSchema a => Text -> Either DeserializerErrorString a`.

The readme currently shows how to product types, but it doesn't show sum types, which are also super important in Haskell.

**Comment by NorfairKing** [comment]
Sum types are a pain in the butt.
If they're enums, there's a function for that.
If they're not, you use something like `eitherCodec`.

The complexity has something to do with a codec being 3 directional: encoding, decoding, and documenting.

PR welcome.

**Comment by NorfairKing** [comment]
Sum types have been documented now, https://hackage.haskell.org/package/autodocodec-0.1.0.0/docs/Autodocodec.html#g:14
