### ISSUE TITLE
Custom error messages for enums (when parsing JSON)?

### ISSUE THREAD

**Issue by trvulkov** [NorfairKing/autodocodec#50]
If we have a simple enum type and use `shownBoundedEnumCodec` for its codec, failures during parsing will produce long errors about disjoint unions, like this:

```
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}

import Autodocodec
import Data.Aeson

data Fruit = Apple | Orange | Banana | Melon
  deriving (Show, Eq, Enum, Bounded)
  deriving (ToJSON, FromJSON) via (Autodocodec Fruit)

instance HasCodec Fruit where codec = shownBoundedEnumCodec

main :: IO ()
main = do
  case eitherDecode @Fruit "\"Lemon\"" of
    Left msg -> putStrLn msg
    Right _ -> putStrLn "fine"
```

```
Error in $:
Both branches of a disjoint union failed:
Left:   Error in $: Expected "Apple" but got "Lemon"
Right:  Error in $: Both branches of a disjoint union failed:
Left:   Error in $: Expected "Orange" but got "Lemon"
Right:  Error in $: Both branches of a disjoint union failed:
Left:   Error in $: Expected "Banana" but got "Lemon"
Right:  Error in $: Expected "Melon" but got "Lemon"
```

Is there a way to overwrite these with some kind of custom error message? This specific format of error seems to come from [`parseJSONContextVia`](https://github.com/NorfairKing/autodocodec/blob/master/autodocodec/src/Autodocodec/Aeson/Decode.hs#L114), and is inherent to the `EitherCodec` that enums are implemented as, but is there some way to bypass this?

For comparison, the default generic `FromJSON` instance produces this, which is pretty close to what I need, but of course by using that (through `codecViaAeson`) we lose out on the good documentation:
```
Error in $: parsing Main.Fruit failed, expected one of the tags ["Apple","Orange","Banana","Melon"], but found tag "Lemon"
```

**Comment by NorfairKing** [comment]
@trvulkov there's no way to do this currently but I'm open to improvements :)
