### ISSUE TITLE
How to use `oneOf` instead of `anyOf` for `eitherCodec`

### ISSUE THREAD

**Issue by joelfisch** [NorfairKing/autodocodec#7]
Hey there,

I have the following codec: 

```haskell
data Ainur
  = Valar Text
  | Mayar Text
  deriving stock (Eq, Ord, Show, Generic)
  deriving (FromJSON, ToJSON, OpenAPI.ToSchema) via (Autodocodec Ainur)

instance HasCodec Ainur where
  codec =
    dimapCodec f g $
      eitherCodec
        (object "Valar" $ requiredField "domain" "Domain which the Valar rules over")
        (object "Mayar" $ requiredField "name" "Name of the Mayar")
    where
      f = \case
        Left domain -> Valar domain
        Right name -> Mayar name
      g = \case
        Valar domain -> Left domain
        Mayar name -> Right name
```

which generates the following OpenAPI 3 schema (the schemas for `Valar` and `Mayar` are omitted for brevity):

```json
{
    "anyOf": [
        {
            "$ref": "#/components/schemas/Valar"
        },
        {
            "$ref": "#/components/schemas/Mayar"
        }
    ],
    "additionalProperties": true
}
```

The `anyOf` schema is not the one I am aiming for in this case as this implies that the following JSON object is valid:

```json
{"domain":"Life","name":"Olorin"}
```

As the codec actually successfully decodes this object as `Valar "Life"`, the current schema is correct for the codec but my question is now, if there is a way to define a codec which acts as a `oneOf` and rejects objects which contain additional properties (the resulting schema should not use `additionalProperties` either in that case). Thank you for your help!

**Comment by NorfairKing** [comment]
Hi! The reason that the schema uses `anyOf` instead of `oneOf` is that there is no way to guarantee that the codecs are disjunct.
For example, if you have this codec: `eitherCodec (codec :: JSONCodec Int) (codec :: JSONCodec Int) :: JSONCodec (Either Int Int)`, and it would generate a `oneOf`, then it couldn't match anything.
I'm not sure if this is fixable in general. Do you have any ideas?

**Comment by joelfisch** [comment]
This a very good point. I do not think it is possible to automatically distinguish between `anyOf` and `oneOf` and it would be only useful for multiple `ObjectCodec`.

My main concern here is that an OpenAPI specification is a communication to the client mainly about what you should send to the API and not so much what you can send without breaking anything. E. g., it is nice for the user of the API to know that they can send arbitrary additional properties and it won't crash (but neither be useful) but somewhat shadows the schemas where you actually want the user to submit additional properties (which will be used).

I think it could be reasonable to allow the user to specify whether it should be a `oneOf` or `anyOf` (and have `additionalProperties` or not) as it would enable them to communicate their intent. But I can completely understand if you do not want anything in here which only reflects intent and not actual behavior (I do not think it would be reasonable to effectively try to parse with every supplied codec just to validate `oneOf` and throw if multiple codecs successfully parse). Maybe one should write the OpenAPI specification by hand in this case. What do you think?

**Comment by NorfairKing** [comment]
If I understand correctly, I think this test is the big issue: https://github.com/NorfairKing/autodocodec/blob/master/autodocodec-api-usage/test/Autodocodec/OpenAPISpec.hs#L98-L120
We could get rid of that test, and the `additionalProperties`. What do you think?
You would still have `anyOf` instead of `oneOf`, though ..

**Comment by NorfairKing** [comment]
Oh! Another option would be to have a second version of `EitherCodec` that requires disjunct-ness while parsing.

**Comment by NorfairKing** [comment]
Fixed in development.
